### ISSUE TITLE
Bug while executing python code

### ISSUE THREAD

**Issue by SebastianZug** [LiaScript/CodeRunner#1]
Hi,

I embedded the following code snippet in my LiaScript document:

```
import pandas as pd
import numpy as np

#Random numbers as examplary content provided by `numpy` package  
s = pd.Series(np.random.randn(5))
print(s)
```
@LIA.eval(`["main.py"]`, `none`, `python3 main.py`)

The coderunner quits with

```
missing ] after element list
```

The error is caused by the "´" in the comment. After deleting them, everything works fine.

**Comment by andre-dietrich** [comment]
@SebastianZug Thanks for the report ;-) ... The current version of LiaScript and the CodeRunner should now work as expected. It was indeed caused by the backtiks. Elm and JavaScript have different types of string escapes, which caused this problem. There was another report for Haskell, which had the same problem ... 

``` haskell
main = do
  putStrLn $ show $ 9 `mod` 2
```
